
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 11 16:23:15 EST 2018
//----------------------------------------------------

package smpl.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GRT = 17;
  public static final int EXPT = 14;
  public static final int DOUBLE = 38;
  public static final int INTEGER = 34;
  public static final int LPAREN = 2;
  public static final int SEMI = 4;
  public static final int PRINTLN = 33;
  public static final int LST = 18;
  public static final int MINUS = 10;
  public static final int CHARACTER = 37;
  public static final int RPAREN = 3;
  public static final int NIL = 41;
  public static final int COMMA = 5;
  public static final int LAZY = 32;
  public static final int CALL = 31;
  public static final int BAND = 22;
  public static final int DIV = 12;
  public static final int BNOT = 24;
  public static final int PLUS = 9;
  public static final int ASSIGN = 15;
  public static final int IF = 25;
  public static final int DOT = 6;
  public static final int GQT = 19;
  public static final int EOF = 0;
  public static final int FALS = 40;
  public static final int error = 1;
  public static final int MUL = 11;
  public static final int MOD = 13;
  public static final int TRU = 39;
  public static final int NQT = 21;
  public static final int EQV = 16;
  public static final int BOR = 23;
  public static final int LBRACE = 7;
  public static final int ELSE = 27;
  public static final int VARIABLE = 35;
  public static final int LET = 28;
  public static final int THEN = 26;
  public static final int RBRACE = 8;
  public static final int STRING = 36;
  public static final int PROC = 30;
  public static final int DEF = 29;
  public static final int LQT = 20;
}

