
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 23 14:05:03 EST 2018
//----------------------------------------------------

package smpl.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LVEC = 12;
  public static final int GRT = 22;
  public static final int EXPT = 19;
  public static final int RBRAK = 11;
  public static final int DOUBLE = 43;
  public static final int INTEGER = 39;
  public static final int LPAREN = 2;
  public static final int SEMI = 4;
  public static final int PRINTLN = 38;
  public static final int LST = 23;
  public static final int MINUS = 15;
  public static final int CHARACTER = 42;
  public static final int RPAREN = 3;
  public static final int NIL = 46;
  public static final int LAZY = 37;
  public static final int COMMA = 5;
  public static final int CALL = 36;
  public static final int BAND = 27;
  public static final int DIV = 17;
  public static final int BNOT = 29;
  public static final int PLUS = 14;
  public static final int ASSIGN = 20;
  public static final int IF = 30;
  public static final int DOT = 6;
  public static final int GQT = 24;
  public static final int RVEC = 13;
  public static final int EOF = 0;
  public static final int FALS = 45;
  public static final int error = 1;
  public static final int MUL = 16;
  public static final int MOD = 18;
  public static final int TRU = 44;
  public static final int NQT = 26;
  public static final int EQV = 21;
  public static final int BOR = 28;
  public static final int LBRACE = 8;
  public static final int ELSE = 32;
  public static final int VARIABLE = 40;
  public static final int COLN = 7;
  public static final int LET = 33;
  public static final int LBRAK = 10;
  public static final int THEN = 31;
  public static final int RBRACE = 9;
  public static final int STRING = 41;
  public static final int PROC = 35;
  public static final int DEF = 34;
  public static final int LQT = 25;
}

